name: CI-2

description: actions

on:
  push:
    branches:
      - main

runs:
  using:
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Repo auschecke
            uses: actions/checkout@v4

          - name: Linting
            run: echo "Hier kommt das Linting"

          - name: Tests
            run: echo "Hier kommen die Tests"